author: Sarah Cohen
date: last-modified
title: Untitled
subtitle: ""

project:
  type: website
  output-dir: docs


format:
  scdefault-html:   #/ requires _quarto.yml in root of project folder
    code-overflow: wrap
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem
    toc: true

execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: false
  include: true
  eval: false
  freeze: auto

extensions:
  - _extensions/scdefault
  - _extensions/coatless-quarto/custom-callout


engine:
  knitr

website:
  navbar:
    background: primary
    left:
      - text: "Home"
        href: documentation/documentation.qmd
      - text: "Common data"
        href: documentation/docs-alldata.qmd
      - text: "Arrests"
        href: documentation/docs-arrests.qmd
      - href: documentation/docs-backgrounder.qmd
        text: "Backgrounder"


custom-callout:
  todo:
    color: "#325d88"
    title: "TODO"
    icon: ""
  question:
    color: red
    title: "Questions"

filters:
- custom-callout
