author: Sarah Cohen
date: last-modified
title: Untitled
subtitle: ""

format:
  scdefault-html:   #/ requires _quarto.yml in root of project folder
    code-overflow: wrap
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem
    toc: true

execute:
  echo: false
  warning: false
  message: false
  error: true
  cache: false
  include: true
  eval: true

extensions:
  - _extensions/scdefault
  - _extensions/coatless-quarto/custom-callout


engine:
  knitr

