# all of the other stuff is in the main _quarto.yml
format:
  scdefault-html:
    toc: true
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
    callout-icon: false

